
package org.bank.credit.web.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-01-15T18:38:13.439+01:00
 * Generated source version: 3.1.8
 * 
 */
public final class CreditScoreService_CreditScoreServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.web.credit.bank.org/", "CreditScoreService");

    private CreditScoreService_CreditScoreServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CreditScoreService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CreditScoreService_Service ss = new CreditScoreService_Service(wsdlURL, SERVICE_NAME);
        CreditScoreService port = ss.getCreditScoreServicePort();  
        
        {
        System.out.println("Invoking creditScore...");
        java.lang.String _creditScore_ssn = "";
        int _creditScore__return = port.creditScore(_creditScore_ssn);
        System.out.println("creditScore.result=" + _creditScore__return);


        }

        System.exit(0);
    }

}
