package org.bank.credit.web.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-01-15T18:38:13.536+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://service.web.credit.bank.org/", name = "CreditScoreService")
@XmlSeeAlso({ObjectFactory.class})
public interface CreditScoreService {

    @WebMethod
    @Action(input = "http://service.web.credit.bank.org/CreditScoreService/creditScoreRequest", output = "http://service.web.credit.bank.org/CreditScoreService/creditScoreResponse")
    @RequestWrapper(localName = "creditScore", targetNamespace = "http://service.web.credit.bank.org/", className = "org.bank.credit.web.service.CreditScore")
    @ResponseWrapper(localName = "creditScoreResponse", targetNamespace = "http://service.web.credit.bank.org/", className = "org.bank.credit.web.service.CreditScoreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int creditScore(
        @WebParam(name = "ssn", targetNamespace = "")
        java.lang.String ssn
    );
}
