
package getBanks.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RuleBaseImplementationService", targetNamespace = "http://soap.webservice/", wsdlLocation = "http://localhost:9999/ws/rule-base?wsdl")
public class RuleBaseImplementationService
    extends Service
{

    private final static URL RULEBASEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException RULEBASEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName RULEBASEIMPLEMENTATIONSERVICE_QNAME = new QName("http://soap.webservice/", "RuleBaseImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/rule-base?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RULEBASEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        RULEBASEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public RuleBaseImplementationService() {
        super(__getWsdlLocation(), RULEBASEIMPLEMENTATIONSERVICE_QNAME);
    }

    public RuleBaseImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RULEBASEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public RuleBaseImplementationService(URL wsdlLocation) {
        super(wsdlLocation, RULEBASEIMPLEMENTATIONSERVICE_QNAME);
    }

    public RuleBaseImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RULEBASEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public RuleBaseImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RuleBaseImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RuleBaseInterface
     */
    @WebEndpoint(name = "RuleBaseImplementationPort")
    public RuleBaseInterface getRuleBaseImplementationPort() {
        return super.getPort(new QName("http://soap.webservice/", "RuleBaseImplementationPort"), RuleBaseInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RuleBaseInterface
     */
    @WebEndpoint(name = "RuleBaseImplementationPort")
    public RuleBaseInterface getRuleBaseImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.webservice/", "RuleBaseImplementationPort"), RuleBaseInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RULEBASEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw RULEBASEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return RULEBASEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
