
package getBanks.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RuleBaseInterface", targetNamespace = "http://soap.webservice/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RuleBaseInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.soap.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.webservice/RuleBaseInterface/getBanksByCreditScoreRequest", output = "http://soap.webservice/RuleBaseInterface/getBanksByCreditScoreResponse")
    public ArrayList getBanksByCreditScore(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.webservice/RuleBaseInterface/getBanksByCreditScoreJsonRequest", output = "http://soap.webservice/RuleBaseInterface/getBanksByCreditScoreJsonResponse")
    public String getBanksByCreditScoreJson(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
